### ISSUE TITLE
Facility Self Checkin via Link

### ISSUE THREAD

**Issue by blakenan-bellese** [CodeForBaltimore/Healthcare-Rollcall#154]
### User Story
As a Facility User
I'd like to respond to checkin questions directly
So that I can provide timely info to the city when most convenient to me

### Acceptance Criteria
- [x] Facilities receive emails which will automatically log them into HealthCare RollCall UI - See #158 for details about the new facility role.
- [x] Emails will contain a link, which includes an embedded token.  
- [x] Link leverages embedded token which automatically logs in as facility user for that facility
- [x] Embedded tokens are specific to the Date sent and the Facility associated with the token.  
- [x] Email is sent to each contact of each facility.  If a contact is associated with more than one facility, they will receive multiple emails with different tokens.
- [x] Email is sent to each contact of each facility.  If a facility is associated with more than one contact, each contact will receive the same token.
- [x] Emails are generated by the Outreach Coordinator - #157, #155
- [x] Link from email allows facility user to complete a check-in with questions associated with their facility type
- [x] Access is limited to JUST the check-in questionnaire
- [x] User is logged in via a new role specific to facility user - #158
- [x] Once check in is submitted user is logged out and link is invalidated.
- [x] Link is good for 24 hours from send 
- [x] Email automatically logs facility role in.  The facility role will not need to enter user/pass to log in.  They will click the link and see the Facility check-in page appropriate for them only.
- [x] Facility should be able to view their responses before submitting
- [ ] Facility should be able to revise only their own contact info (revise phone number and email)
- [x] Facility cannot view/edit other contacts
- [x] Facility should be able to edit their responses before their session ends
- [x] Session should have a limited timeframe (2-4 hours)
- [x] Facility Check-In page should show the Facility Name where the userid is now shown in UI
- [ ] 

### Notes
Thinking that we may want to notify other contacts when checkin is complete and possibly invalidate their links too. Not sure how many facilities have multiple valid email contacts.  

In future show history of many checkins for a factility.

**Comment by msmith125** [comment]
Performed some quick testing with the Simpson data.  Was able to get email sent, perform a check-in, refresh and perform another check-in and validate that the data was written to the entity table.  Followed these steps.
1.) update local env to Bmore PR 181 and HCRollcall PR 167
2.) updated .env to include-
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=no-reply@codeforbaltimore.org
SMTP_PASSWORD=nL7y5%o1LOWEKAH
TEST_EMAIL=msmith@bellese.io
3.) updated Leftorium to be an "Assisted Living Facility"
4.) added a New Contact to the Leftorium with my email via UI.
You cannot give a title when you add a new contact so I unlinked and then relinked this contact with my email with title "Primary Contact"
5.) Verified entity and contact were linked with RelationshipTitle "Primary Contact"
6.) using swagger doc, tried to send email using "Try it out" with updated Parms for
{
  "entityIds": [
    "05533f95-b440-4f9d-876d-653636dce0c8"
  ],
  "contactIds": [
    "05533f95-b440-4f9d-876d-653636dce0c8"
  ],
  "relationshipTitle": [
    "Primary Contact"
  ]
}
7.) I could not get it to work when using entityids or contactids.  Tried all combinations.  I only was able to send email when using just:
{

  "relationshipTitle": [
    "Primary Contact"
  ]
}
8.) Received the email and was able to perform a check-in.
9.) Refreshed and saw previous check-in was completed and performed another check-in.
10.) Queried Entities table and verified two check-ins were completed.
11.) tried to log into front-end as homer simpson but it seems that i am still a facility and cannot see contact/etc (Chrome).  Cleared cache, logged in as homer and verified the check-ins.

It seems to be working with some minor issues. More detailed testing is definitely needed.  Just wanted to share what I was able to complete.  I can test more this weekend if needed.  Thanks.

**Comment by revjtanton** [comment]
I added the contact and entity id stuff early on but have pushed that functionality back to a future release. I've updated swagger to reflect this.

**Comment by msmith125** [comment]
Jason,

This looks really good.  I tested and confirmed that:
1) The same contact can have multiple entities and will receive an email for each one
2) The same entity can have multiple contacts and emails are sent based on relationshipType
3) Emails can be sent based on a single relationshipType or to all if no parms are sent
4) Check-ins are stored properly in Entities.checkIn and accumulate correctly (created up to 6 and they are were stored in Entities.checkin correctly)
5) Previous check-ins are shown in the UI and can be reviewed and look accurate
6) Previous check-ins are shown when you click on the link in the email
7) The same email address can be used for multiple contacts and emails are sent correctly
8) An admin of the system can perform check-ins and can view check-ins done via email link
9) When you click on check-in link via the email, you can see previous check-ins done by an admin via the UI

The only thing that I found to be confusing is that after a check-in is completed via the email link, no success message is displayed, it just appears to log the user out.  I think a success message or success email may be helpful - #169 

Overall, my opinion is that this looks great.  I can validate that the check-in link expires after 24 hours tomorrow morning.  Please let me know if there is anything else you would like for me to test related to this.  

Thanks!
Marie
